-- Create EQUIPMENT_IMAGES table for equipment image storage
CREATE TABLE IF NOT EXISTS EQUIPMENT_IMAGES (
  EQUIPMENT_ID VARCHAR(50) NOT NULL,
  FILENAME VARCHAR(255) NOT NULL,
  UPLOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (EQUIPMENT_ID),
  INDEX idx_equipment_id (EQUIPMENT_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;