GET http://localhost:3002/corrective
###
GET http://localhost:3002/corrective/0001209
###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "username": "TKENT",
    "password": "asd"
}
###

POST http://localhost:3003/user/login
Content-Type: application/json

{
    "username": "TKENT",
    "password": "$2b$10$lwOzJ"
}

###
GET http://localhost:3003/csr/nextCSRId

###
GET http://localhost:3003/input/nextId

###
GET http://localhost:3003/ssr/nextSSRId

###
GET http://localhost:3003/reports

###
PUT http://localhost:3003/requests/0000092
Content-Type: application/json

{
    "CLOSED": "Y",
    "CLOSED_DATE": "2025-02-19",
    "DECISION": "A",
    "DECISION_DATE": "2025-02-19",
    "DOCUMENT_ID": "CI-QSP-8500",
    "REQUEST_ID": "0000092",
    "REVISION_LEVEL": "N",
    "REVISION_DATE": "2025-02-19",
    "MODIFIED_BY": "TKENT",
    "MODIFIED_DATE": "2025-02-19"
}
###
PUT http://localhost:3003/csr/incrementId

###
GET http://localhost:3003/attendance/nextId
###
GET http://localhost:3003/expiry
###
GET http://localhost:3003/expiry/nextId
###
GET http://localhost:3003/calibrate
