-- Create CERT_REVISION table for tracking certificate changes
CREATE TABLE IF NOT EXISTS CERT_REVISION (
    WOREV_ID INT AUTO_INCREMENT PRIMARY KEY,
    WO_NO VARCHAR(50) NOT NULL,
    SECTION VARCHAR(50) NOT NULL,
    SERIAL_NUMBER VARCHAR(50),
    REVISION_TYPE ENUM('EDIT', 'DELETE') NOT NULL,
    ORIGINAL_DATA JSON,
    NOTES TEXT NOT NULL,
    CREATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATE_BY VARCHAR(100),
    INDEX idx_wo_no (WO_NO),
    INDEX idx_section (SECTION),
    INDEX idx_create_date (CREATE_DATE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
