-- Subject-level resources. No availability or operability state is stored.
CREATE TABLE IF NOT EXISTS RESOURCE (
  ID INT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(255) NOT NULL,
  TYPE ENUM('EQUIPMENT', 'FACILITY', 'CONDITION', 'PERSON', 'MATERIAL') NOT NULL,
  NOTES TEXT NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_RESOURCE_NAME_TYPE (NAME, TYPE)
);

CREATE TABLE IF NOT EXISTS SUBJECT_RESOURCE_REQUIREMENT (
  ID INT NOT NULL AUTO_INCREMENT,
  SUBJECT_ID VARCHAR(100) NOT NULL,
  RESOURCE_ID INT NOT NULL,
  REQUIRED_QUANTITY DECIMAL(12, 3) NULL,
  PRIMARY KEY (ID),
  UNIQUE KEY UQ_SUBJECT_RESOURCE (SUBJECT_ID, RESOURCE_ID),
  CONSTRAINT FK_SUBJECT_RESOURCE_RESOURCE
    FOREIGN KEY (RESOURCE_ID) REFERENCES RESOURCE (ID)
    ON DELETE CASCADE
);

CREATE INDEX IX_SUBJECT_RESOURCE_SUBJECT
  ON SUBJECT_RESOURCE_REQUIREMENT (SUBJECT_ID);
