-- Special process form storage (save-when-done) for chem film/passivation
-- MySQL 8+

CREATE TABLE IF NOT EXISTS SPECIAL_PROCESS_FORM (
  FORM_RECORD_ID BIGINT NOT NULL AUTO_INCREMENT,
  FORM_DEFINITION_ID VARCHAR(20) NOT NULL,
  FORM_INSTANCE_ID VARCHAR(80) NOT NULL,
  SERIES VARCHAR(10) NOT NULL,
  SEQUENCE_CODE VARCHAR(10) NOT NULL,
  FORM_LABEL VARCHAR(120) NOT NULL,

  WORK_ORDER_RAW VARCHAR(40) NOT NULL,
  WORK_ORDER_JOB VARCHAR(20) NOT NULL,
  WORK_ORDER_SUFFIX VARCHAR(10) NOT NULL,
  PART_NUMBER VARCHAR(40) NULL,
  PART_DESCRIPTION VARCHAR(255) NULL,

  QTY_ACCEPTED INT NOT NULL DEFAULT 0,
  QTY_REJECTED INT NOT NULL DEFAULT 0,
  NOTES TEXT NULL,

  PROCESS_TYPE VARCHAR(20) NOT NULL,
  PROCESS_DATE DATE NULL,
  STATUS VARCHAR(20) NOT NULL DEFAULT 'SAVED',

  CREATED_BY VARCHAR(50) NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_BY VARCHAR(50) NULL,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (FORM_RECORD_ID),
  UNIQUE KEY UQ_SPECIAL_PROCESS_INSTANCE (FORM_INSTANCE_ID),
  KEY IX_SPECIAL_PROCESS_WORK_ORDER (WORK_ORDER_JOB, WORK_ORDER_SUFFIX),
  KEY IX_SPECIAL_PROCESS_PART (PART_NUMBER),
  KEY IX_SPECIAL_PROCESS_DEFINITION (FORM_DEFINITION_ID),
  KEY IX_SPECIAL_PROCESS_STATUS (STATUS),
  KEY IX_SPECIAL_PROCESS_CREATED_AT (CREATED_AT)
);

CREATE TABLE IF NOT EXISTS SPECIAL_PROCESS_STEP_VALUE (
  STEP_VALUE_ID BIGINT NOT NULL AUTO_INCREMENT,
  FORM_RECORD_ID BIGINT NOT NULL,

  STEP_INDEX INT NOT NULL,
  STEP_TITLE VARCHAR(120) NOT NULL,
  IS_OPTIONAL_BLOCK_STEP TINYINT(1) NOT NULL DEFAULT 0,

  RANGE_INDEX INT NOT NULL DEFAULT 0,
  RANGE_LABEL VARCHAR(40) NULL,
  RANGE_UOM VARCHAR(20) NULL,
  SPEC_MIN DECIMAL(12, 4) NULL,
  SPEC_MAX DECIMAL(12, 4) NULL,

  INPUT_TYPE VARCHAR(20) NOT NULL DEFAULT 'number',
  ACTUAL_NUMERIC DECIMAL(12, 4) NULL,
  ACTUAL_TEXT VARCHAR(255) NULL,
  PASS_FAIL VARCHAR(10) NULL,

  REQUIREMENT_TEXT VARCHAR(255) NULL,

  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (STEP_VALUE_ID),
  CONSTRAINT FK_SPECIAL_PROCESS_STEP_FORM
    FOREIGN KEY (FORM_RECORD_ID) REFERENCES SPECIAL_PROCESS_FORM(FORM_RECORD_ID)
    ON DELETE CASCADE,
  KEY IX_STEP_FORM (FORM_RECORD_ID),
  KEY IX_STEP_TITLE (STEP_TITLE),
  KEY IX_STEP_INDEX (FORM_RECORD_ID, STEP_INDEX, RANGE_INDEX)
);

CREATE TABLE IF NOT EXISTS SPECIAL_PROCESS_FORM_AUDIT (
  AUDIT_ID BIGINT NOT NULL AUTO_INCREMENT,
  FORM_RECORD_ID BIGINT NOT NULL,
  ACTION_TYPE VARCHAR(30) NOT NULL,
  ACTION_BY VARCHAR(50) NULL,
  ACTION_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ACTION_NOTE VARCHAR(255) NULL,
  SNAPSHOT_JSON LONGTEXT NULL,

  PRIMARY KEY (AUDIT_ID),
  CONSTRAINT FK_SPECIAL_PROCESS_AUDIT_FORM
    FOREIGN KEY (FORM_RECORD_ID) REFERENCES SPECIAL_PROCESS_FORM(FORM_RECORD_ID)
    ON DELETE CASCADE,
  KEY IX_AUDIT_FORM (FORM_RECORD_ID),
  KEY IX_AUDIT_ACTION_AT (ACTION_AT)
);

-- Suggested status values:
-- SAVED, VOID

-- Suggested ACTION_TYPE values:
-- CREATE_SAVE, UPDATE_SAVE, LOOKUP_PART, REOPEN, VOID
