-- Apply after create_special_process_tables.sql if tables already exist with DRAFT/SUBMITTED semantics

ALTER TABLE SPECIAL_PROCESS_FORM
  ALTER STATUS SET DEFAULT 'SAVED';

UPDATE SPECIAL_PROCESS_FORM
SET STATUS = 'SAVED'
WHERE STATUS IN ('DRAFT', 'SUBMITTED');

UPDATE SPECIAL_PROCESS_FORM_AUDIT
SET ACTION_TYPE = 'CREATE_SAVE'
WHERE ACTION_TYPE = 'CREATE_DRAFT';

UPDATE SPECIAL_PROCESS_FORM_AUDIT
SET ACTION_TYPE = 'UPDATE_SAVE'
WHERE ACTION_TYPE = 'UPDATE_DRAFT';

UPDATE SPECIAL_PROCESS_FORM_AUDIT
SET ACTION_TYPE = 'UPDATE_SAVE'
WHERE ACTION_TYPE = 'SUBMIT';
