-- Migration: Consolidate INPUTS_NOTIFY, NCM_NOTIFY, CORRECTIVE_NOTIFY into EMAIL_HISTORY
-- Created: 2026-03-18
-- This script archives old notify tables and prepares for centralized EMAIL_HISTORY logging

-- Step 1: Create archive tables
CREATE TABLE IF NOT EXISTS INPUTS_NOTIFY_ARCHIVE AS SELECT * FROM INPUTS_NOTIFY;
CREATE TABLE IF NOT EXISTS NCM_NOTIFY_ARCHIVE AS SELECT * FROM NCM_NOTIFY;
CREATE TABLE IF NOT EXISTS CORRECTIVE_NOTIFY_ARCHIVE AS SELECT * FROM CORRECTIVE_NOTIFY WHERE 1=0; -- Create empty if table doesn't exist

-- Step 2: Migrate INPUTS_NOTIFY data to EMAIL_HISTORY
INSERT INTO EMAIL_HISTORY (APP_MODULE, APP_ID, RECIPIENT_EMAIL, SENT_DATE, EMAIL_STATUS, EMAIL_TYPE, NOTES)
SELECT 
  'INPUT' AS APP_MODULE,
  INPUT_ID AS APP_ID,
  ASSIGNED_TO AS RECIPIENT_EMAIL,
  NOTIFIED_DATE AS SENT_DATE,
  'SENT' AS EMAIL_STATUS,
  CASE WHEN ACTION = 'A' THEN 'ASSIGNMENT' 
       WHEN ACTION = 'C' THEN 'CLOSEOUT' 
       ELSE ACTION END AS EMAIL_TYPE,
  CONCAT('Migrated from INPUTS_NOTIFY - Action: ', ACTION) AS NOTES
FROM INPUTS_NOTIFY
WHERE NOT EXISTS (
  SELECT 1 FROM EMAIL_HISTORY eh 
  WHERE eh.APP_MODULE = 'INPUT' 
  AND eh.APP_ID = INPUTS_NOTIFY.INPUT_ID 
  AND eh.SENT_DATE = INPUTS_NOTIFY.NOTIFIED_DATE
);

-- Step 3: Migrate NCM_NOTIFY data to EMAIL_HISTORY
INSERT INTO EMAIL_HISTORY (APP_MODULE, APP_ID, RECIPIENT_EMAIL, SENT_DATE, EMAIL_STATUS, EMAIL_TYPE, NOTES)
SELECT 
  'NCM' AS APP_MODULE,
  NCM_ID AS APP_ID,
  ASSIGNED_TO AS RECIPIENT_EMAIL,
  NOTIFIED_DATE AS SENT_DATE,
  'SENT' AS EMAIL_STATUS,
  CASE WHEN ACTION = 'A' THEN 'ASSIGNMENT' 
       WHEN ACTION = 'C' THEN 'CLOSEOUT' 
       ELSE ACTION END AS EMAIL_TYPE,
  CONCAT('Migrated from NCM_NOTIFY - Action: ', ACTION) AS NOTES
FROM NCM_NOTIFY
WHERE NOT EXISTS (
  SELECT 1 FROM EMAIL_HISTORY eh 
  WHERE eh.APP_MODULE = 'NCM' 
  AND eh.APP_ID = NCM_NOTIFY.NCM_ID 
  AND eh.SENT_DATE = NCM_NOTIFY.NOTIFIED_DATE
);

-- Step 4: Truncate old notification tables (preserve data in archives)
-- TRUNCATE TABLE INPUTS_NOTIFY;
-- TRUNCATE TABLE NCM_NOTIFY;
-- TRUNCATE TABLE CORRECTIVE_NOTIFY;

-- Step 5: (Optional) Drop old tables after verification
-- DROP TABLE INPUTS_NOTIFY;
-- DROP TABLE NCM_NOTIFY;
-- DROP TABLE CORRECTIVE_NOTIFY;

-- Verification queries to check migration
-- SELECT 'INPUTS_NOTIFY' as source, COUNT(*) as count FROM INPUTS_NOTIFY_ARCHIVE
-- UNION ALL
-- SELECT 'NCM_NOTIFY', COUNT(*) FROM NCM_NOTIFY_ARCHIVE
-- UNION ALL
-- SELECT 'EMAIL_HISTORY (migrated INPUT)', COUNT(*) FROM EMAIL_HISTORY WHERE APP_MODULE = 'INPUT'
-- UNION ALL
-- SELECT 'EMAIL_HISTORY (migrated NCM)', COUNT(*) FROM EMAIL_HISTORY WHERE APP_MODULE = 'NCM';
