-- Adds the technician-entered process date to special process forms
USE quality;

ALTER TABLE SPECIAL_PROCESS_FORM
  ADD COLUMN PROCESS_DATE DATE NULL AFTER PROCESS_TYPE;

UPDATE SPECIAL_PROCESS_FORM
SET PROCESS_DATE = DATE(CREATED_AT)
WHERE PROCESS_DATE IS NULL;
