-- Create PERSON_SKILLS table for tracking employee/person competencies
CREATE TABLE IF NOT EXISTS PERSON_SKILLS (
  PERSON_SKILL_ID INT AUTO_INCREMENT PRIMARY KEY,
  PEOPLE_ID VARCHAR(255) NOT NULL,
  JOB_TITLE VARCHAR(255) NOT NULL,
  COMPETENCY VARCHAR(100) NOT NULL COMMENT 'Basic, Intermediate, Advanced, Expert',
  CERT_DATE DATE,
  CERT_BY VARCHAR(100),
  NOTES LONGTEXT,
  ASSIGN_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,
  REQUESTED_BY VARCHAR(100),
  MODIFIED_DATE DATETIME ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_people_id (PEOPLE_ID),
  INDEX idx_job_title (JOB_TITLE),
  UNIQUE KEY unique_person_job (PEOPLE_ID, JOB_TITLE)
);
