-- Revisioned inspection reminders keyed by Global operation code.
CREATE TABLE IF NOT EXISTS JOBBER_REMINDER (
  JOBBER_ID VARCHAR(7) NOT NULL,
  REVISION INT NOT NULL,
  OPERATION_CODE VARCHAR(50) NOT NULL,
  REMINDER_TEXT TEXT NOT NULL,
  ACTIVE TINYINT(1) NOT NULL DEFAULT 1,
  CREATE_BY VARCHAR(50),
  CREATE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  MODIFIED_BY VARCHAR(50),
  MODIFIED_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (JOBBER_ID, REVISION),
  INDEX idx_jobber_reminder_operation (OPERATION_CODE),
  INDEX idx_jobber_reminder_active (ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO SYSTEM_IDS (TABLE_NAME, CURRENT_ID)
SELECT 'JOBBER_REMINDER', '0000000'
WHERE NOT EXISTS (
  SELECT 1 FROM SYSTEM_IDS WHERE TABLE_NAME = 'JOBBER_REMINDER'
);
